[hasura]
  version = "v2.36.0-ce"
  adminSecret = "{{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}"
  webhookSecret = "{{ secrets.NHOST_WEBHOOK_SECRET }}"
  [[hasura.jwtSecrets]]
    type = "HS256"
    key = "{{ secrets.HASURA_JWT_SECRET }}"
  [hasura.settings]
    corsDomain = ["*"]
    devMode = true
    enableAllowList = false
    enableConsole = true
    enableRemoteSchemaPermissions = false
    enabledAPIs = ["metadata", "graphql", "pgdump", "config"]

  [hasura.logs]
    level = "warn"

  [hasura.events]
    httpPoolSize = 100



[auth]
  version = "0.21.2"

  [auth.redirections]
    clientUrl = "https://ai-workflow-builder-sable.vercel.app"
    allowedUrls = ["http://localhost:3000", "https://ai-workflow-builder-sable.vercel.app"]


  [auth.user]
    [auth.user.roles]
      default = "user"
      allowed = ["user"]




  [auth.session]
    [auth.session.accessToken]
      expiresIn = 900
      [[auth.session.accessToken.customClaims]]
      key = "org-role"
      value = "profile.organizationRole"

[postgres]
  version = "14.6-20230821-1"

[storage]
  version = "0.3.5"
