[hasura]
  version = "v2.49.2-ce"

  [[hasura.jwtSecrets]]
    type = "RS256"
    key = "{{ secrets.NHOST_JWT_PUBLIC_KEY }}"

  [hasura.settings]
    corsDomain = ["*"]
    devMode = true
    enableAllowList = false
    enableConsole = true
    enableRemoteSchemaPermissions = false
    enabledAPIs = ["metadata", "graphql", "pgdump", "config"]

  [hasura.logs]
    level = "warn"

  [hasura.events]
    httpPoolSize = 100

[functions]
  [functions.node]
    version = 22

[auth]

  [auth.redirections]
    clientUrl = "https://ai-workflow-builder-sable.vercel.app"
    allowedUrls = ["http://localhost:3000", "https://ai-workflow-builder-sable.vercel.app"]



  [auth.method.emailPassword]
    emailVerificationRequired = false

  [auth.session]
    [auth.session.accessToken]
      expiresIn = 900

[postgres]
  version = "14.20-20251217-1"

  [postgres.resources]
    [postgres.resources.storage]
      capacity = 1

[storage]
  version = "0.15.0"

[observability]
  [observability.grafana]
    adminPassword = "{{ secrets.GRAFANA_ADMIN_PASSWORD }}"
